//
//  ContentView.swift
//  POC-Rizki
//
//  Created by Muhammad Rizki on 06/10/26.
//

import SwiftUI
import Combine
import CoreMotion
import UIKit

struct ContentView: View {
    @StateObject private var store = MotionResearchStore()
    var body: some View {
        NavigationStack {
            Form {
                sensorSection
                configurationSection
                rhythmSection
                trialSection
                liveDataSection
                resultsSection
                exportSection
                Section("Research reminder") {
                    Text("The phone records only its own motion—not body-part semantics. Repeat each movement 5–10 times per placement. Handheld favors punches; torso placements favor shifts, lean, duck, and rotation.").font(.footnote).foregroundStyle(.secondary)
                }
            }
            .navigationTitle("Motion Lab")
            .alert("Motion unavailable", isPresented: $store.showMotionUnavailable) { Button("OK", role: .cancel) {} } message: { Text("CMDeviceMotion is not available. Test on a physical iPhone.") }
            .onDisappear { store.stopSensor() }
        }
    }
    private var sensorSection: some View { Section("1. Sensor status") { HStack { Circle().fill(store.isSensorRunning ? .green : .gray).frame(width: 10, height: 10); Text(store.isSensorRunning ? "CMDeviceMotion running" : "Sensor stopped"); Spacer(); Button(store.isSensorRunning ? "Stop" : "Start") { store.isSensorRunning ? store.stopSensor() : store.startSensor() }.buttonStyle(.bordered) }; Text("Processed device motion • 50 Hz • physical iPhone required").font(.caption).foregroundStyle(.secondary) } }
    private var configurationSection: some View { Section("2. Trial setup") { Picker("Challenge response", selection: $store.challenge) { ForEach(Challenge.allCases) { Text($0.title).tag($0) } }.pickerStyle(.segmented); Picker("Movement", selection: $store.movement) { ForEach(store.challenge.movements, id: \.self) { Text($0).tag($0) } }; Picker("Phone placement", selection: $store.placement) { ForEach(Placement.allCases) { Text($0.title).tag($0) } }; Picker("Speed", selection: $store.speed) { ForEach(TrialSpeed.allCases) { Text($0.title).tag($0) } }; Stepper("Record duration: \(Int(store.recordingDuration)) seconds", value: $store.recordingDuration, in: 3...5) }.onChange(of: store.challenge) { _, value in store.movement = value.movements[0] } }
    private var rhythmSection: some View { Section("CR1 rhythm test (optional)") { Toggle("Enable beat cue", isOn: $store.rhythmEnabled).disabled(store.challenge != .cr1); if store.rhythmEnabled && store.challenge == .cr1 { Picker("BPM", selection: $store.bpm) { ForEach([60, 90, 120, 150], id: \.self) { Text("\($0) BPM").tag($0) } }; Text("A light haptic marks each beat. Cue timing is written to CSV.").font(.caption).foregroundStyle(.secondary) } } }
    private var trialSection: some View { Section("3. Run trial") { if store.phase != .idle { VStack(alignment: .leading, spacing: 8) { Text(store.phase.message).font(.headline); ProgressView(value: store.progress); Text(store.phase.detail).font(.caption).foregroundStyle(.secondary) } }; Button { store.startTrial() } label: { Label(store.phase == .idle ? "Start Trial" : "Trial in progress", systemImage: "record.circle").frame(maxWidth: .infinity) }.buttonStyle(.borderedProminent).disabled(store.phase != .idle) } }
    private var liveDataSection: some View { Section("4. Live sensor data") { HStack { MetricTile(label: "Acceleration", value: store.live.accelerationMagnitude, unit: "g"); MetricTile(label: "Rotation", value: store.live.rotationMagnitude, unit: "rad/s"); MetricTile(label: "Roll", value: store.live.roll, unit: "°") }; Text("Magnitude uses processed user acceleration (gravity removed). Attitude is in degrees.").font(.caption).foregroundStyle(.secondary) } }
    @ViewBuilder private var resultsSection: some View { if let result = store.latestResult { Section("5. Latest result") { Text("\(result.movement) • \(result.placement) • \(result.speed)").font(.headline); LabeledContent("Duration", value: String(format: "%.2f s", result.duration)); LabeledContent("Samples", value: "\(result.sampleCount)"); LabeledContent("Acceleration", value: String(format: "peak %.2f g · avg %.2f g", result.peakAcceleration, result.averageAcceleration)); LabeledContent("Rotation", value: String(format: "peak %.2f · avg %.2f rad/s", result.peakRotation, result.averageRotation)); LabeledContent("Dominant axes", value: "accel \(result.dominantAccelerationAxis), rotation \(result.dominantRotationAxis)"); LabeledContent("Onset estimate", value: result.onsetText); if let timing = result.timingDifference { LabeledContent("Nearest beat", value: String(format: "%+.0f ms", timing * 1000)) }; Text("Heuristic POC — combines acceleration, rotation, and attitude change; not a validated classifier.").font(.caption).foregroundStyle(.secondary); MotionGraph(samples: result.samples).frame(height: 150) } } }
    private var exportSection: some View { Section("6. Export") { Text("\(store.trials.count) saved trial\(store.trials.count == 1 ? "" : "s") · \(store.totalSamples) samples"); if let url = store.csvURL { ShareLink(item: url) { Label("Share CSV", systemImage: "square.and.arrow.up") } } else { Button { store.prepareCSV() } label: { Label("Prepare CSV export", systemImage: "tablecells") }.disabled(store.trials.isEmpty) }; Button("Clear saved trials", role: .destructive) { store.clearTrials() }.disabled(store.trials.isEmpty) } }
}
private struct MetricTile: View { let label: String; let value: Double; let unit: String; var body: some View { VStack(alignment: .leading) { Text(label).font(.caption).foregroundStyle(.secondary); Text(String(format: "%.2f", value)).font(.headline); Text(unit).font(.caption2).foregroundStyle(.secondary) }.frame(maxWidth: .infinity, alignment: .leading) } }
private struct MotionGraph: View { let samples: [MotionSample]; var body: some View { GeometryReader { proxy in let points = Array(samples.enumerated().filter { $0.offset % max(1, samples.count / 100) == 0 }); let maximum = max(0.01, points.map { max($0.element.accelerationMagnitude, $0.element.rotationMagnitude) }.max() ?? 1); ZStack(alignment: .topLeading) { RoundedRectangle(cornerRadius: 8).fill(Color.secondary.opacity(0.08)); graph(points, values: { $0.accelerationMagnitude }, maximum: maximum, size: proxy.size, color: .blue); graph(points, values: { $0.rotationMagnitude }, maximum: maximum, size: proxy.size, color: .orange); HStack(spacing: 10) { Text("● accel").foregroundStyle(.blue); Text("● rotation").foregroundStyle(.orange) }.font(.caption2).padding(6) } } }
    private func graph(_ points: [(offset: Int, element: MotionSample)], values: (MotionSample) -> Double, maximum: Double, size: CGSize, color: Color) -> some View { Path { path in for (i, point) in points.enumerated() { let x = size.width * CGFloat(i) / CGFloat(max(1, points.count - 1)); let y = size.height * (1 - CGFloat(values(point.element) / maximum)); if i == 0 { path.move(to: CGPoint(x: x, y: y)) } else { path.addLine(to: CGPoint(x: x, y: y)) } } }.stroke(color, lineWidth: 2) }
}

// Kept in this file so a freshly created Xcode project always compiles the model
// together with the view (no additional target-membership step is required).
enum Challenge: String, CaseIterable, Identifiable { case cr1, cr3; var id: String { rawValue }; var title: String { self == .cr1 ? "CR1 Rhythm / Dance" : "CR3 Dungeon / Boxing" }; var movements: [String] { self == .cr1 ? ["Left Arm Up", "Right Arm Up", "Both Arms Up", "Left Arm Side", "Right Arm Side", "Both Arms Side", "Left Arm Forward", "Right Arm Forward", "Arm Cross", "Arm Open", "Arm Swing", "Alternating Arms", "Circular Arm Movement", "Step Left", "Step Right", "Step Forward", "Step Backward", "Side Step", "Double Step", "March", "Knee Raise Left", "Knee Raise Right", "Squat", "Small Jump", "Jump Left", "Jump Right", "Weight Shift Left", "Weight Shift Right", "Lean Left", "Lean Right", "Body Shift Left", "Body Shift Right", "Torso Rotation Left", "Torso Rotation Right", "Bend Forward", "Return Upright", "Bounce", "Left Arm + Left Step", "Left Arm + Right Step", "Both Arms + Step", "Arm + Knee Raise", "Opposite Arm + Opposite Leg", "Alternating Arm + Leg", "Two movements simultaneously", "Three body parts simultaneously"] : ["Dodge Left", "Dodge Right", "Step Left", "Step Right", "Step Forward", "Step Backward", "Lean Left", "Lean Right", "Duck", "Crouch", "Jump", "Quick Stop", "Left to Right", "Right to Left", "Forward to Backward", "Rapid Direction Change", "Slip Left", "Slip Right", "Roll Under", "Pull Back", "Lean Back", "Guard", "Block Left", "Block Right", "Side Step", "Pivot", "Dodge to Return Center", "Left Jab", "Right Jab", "Cross", "Left Straight", "Right Straight", "Left Hook", "Right Hook", "Left Uppercut", "Right Uppercut", "Body Shot Left", "Body Shot Right", "Jab to Cross", "Jab to Cross to Hook", "Jab to Hook", "Cross to Hook", "Hook to Cross", "Uppercut to Hook", "Jab to Cross to Uppercut", "Slip Left to Counter", "Slip Right to Counter", "Duck to Hook", "Pull Back to Cross", "Dodge Left to Counter", "Dodge Right to Counter", "Block to Counter"] } }
enum Placement: String, CaseIterable, Identifiable { case waistCenter = "Waist Center", abdomen = "Abdomen / Stomach", chest = "Chest", rightPocket = "Right Pocket", leftPocket = "Left Pocket", handheld = "Handheld"; var id: String { rawValue }; var title: String { rawValue } }
enum TrialSpeed: String, CaseIterable, Identifiable { case slow, medium, fast; var id: String { rawValue }; var title: String { rawValue.capitalized } }
enum TrialPhase: Equatable { case idle, countdown(Int), recording, saving; var message: String { switch self { case .idle: "Ready"; case .countdown(let s): "Get ready: \(s)"; case .recording: "Recording movement"; case .saving: "Saving trial" } }; var detail: String { switch self { case .countdown: "Hold placement steady and prepare."; case .recording: "Perform the selected movement."; case .saving: "Calculating heuristic result…"; case .idle: "" } } }
struct LiveMotion { var accelerationMagnitude = 0.0; var rotationMagnitude = 0.0; var roll = 0.0 }
struct MotionSample: Identifiable { let id = UUID(); let timestamp: TimeInterval; let wallTime: Date; let challenge, movement, placement, speed: String; let accX, accY, accZ, rotX, rotY, rotZ, roll, pitch, yaw, gravX, gravY, gravZ: Double; let cueTimestamp: Date?; var accelerationMagnitude: Double { sqrt(accX * accX + accY * accY + accZ * accZ) }; var rotationMagnitude: Double { sqrt(rotX * rotX + rotY * rotY + rotZ * rotZ) } }
struct TrialResult: Identifiable { let id = UUID(); let movement, placement, speed: String; let duration: TimeInterval; let sampleCount: Int; let peakAcceleration, averageAcceleration, peakRotation, averageRotation: Double; let dominantAccelerationAxis, dominantRotationAxis, onsetText: String; let timingDifference: TimeInterval?; let samples: [MotionSample] }
@MainActor final class MotionResearchStore: ObservableObject {
    @Published var isSensorRunning = false; @Published var showMotionUnavailable = false; @Published var challenge: Challenge = .cr1; @Published var movement = Challenge.cr1.movements[0]; @Published var placement: Placement = .waistCenter; @Published var speed: TrialSpeed = .medium; @Published var recordingDuration = 4.0; @Published var rhythmEnabled = false; @Published var bpm = 120; @Published var phase: TrialPhase = .idle; @Published var live = LiveMotion(); @Published var latestResult: TrialResult?; @Published var trials: [TrialResult] = []; @Published var csvURL: URL?
    private let manager = CMMotionManager(); private var workingSamples: [MotionSample] = []; private var cues: [Date] = []; private var trialStart: Date?; private var beatTimer: Timer?
    var totalSamples: Int { trials.reduce(0) { $0 + $1.sampleCount } }; var progress: Double { switch phase { case .countdown(let s): Double(3 - s) / 3; case .recording: 0.7; case .saving: 0.95; case .idle: 0 } }
    func startSensor() { guard manager.isDeviceMotionAvailable else { showMotionUnavailable = true; return }; guard !isSensorRunning else { return }; manager.deviceMotionUpdateInterval = 1.0 / 50; manager.startDeviceMotionUpdates(to: .main) { [weak self] motion, _ in guard let self, let motion else { return }; self.consume(motion) }; isSensorRunning = true }
    func stopSensor() { manager.stopDeviceMotionUpdates(); isSensorRunning = false }
    func startTrial() { if !isSensorRunning { startSensor() }; guard isSensorRunning else { return }; csvURL = nil; workingSamples = []; cues = []; phase = .countdown(3); Task { for n in stride(from: 3, through: 1, by: -1) { phase = .countdown(n); try? await Task.sleep(for: .seconds(1)) }; beginRecording(); try? await Task.sleep(for: .seconds(recordingDuration)); finishTrial() } }
    private func beginRecording() { trialStart = Date(); phase = .recording; if rhythmEnabled && challenge == .cr1 { fireBeat(); beatTimer = Timer.scheduledTimer(withTimeInterval: 60 / Double(bpm), repeats: true) { [weak self] _ in self?.fireBeat() } } }
    private func fireBeat() { cues.append(Date()); UIImpactFeedbackGenerator(style: .light).impactOccurred() }
    private func finishTrial() { beatTimer?.invalidate(); beatTimer = nil; phase = .saving; let samples = workingSamples; let duration = Date().timeIntervalSince(trialStart ?? Date()); let result = makeResult(samples: samples, duration: duration); latestResult = result; trials.append(result); phase = .idle }
    private func consume(_ m: CMDeviceMotion) { let a = m.userAcceleration, r = m.rotationRate, g = m.gravity, at = m.attitude; live = LiveMotion(accelerationMagnitude: sqrt(a.x*a.x+a.y*a.y+a.z*a.z), rotationMagnitude: sqrt(r.x*r.x+r.y*r.y+r.z*r.z), roll: at.roll * 180 / .pi); guard phase == .recording else { return }; workingSamples.append(MotionSample(timestamp: m.timestamp, wallTime: Date(), challenge: challenge.title, movement: movement, placement: placement.rawValue, speed: speed.title, accX: a.x, accY: a.y, accZ: a.z, rotX: r.x, rotY: r.y, rotZ: r.z, roll: at.roll, pitch: at.pitch, yaw: at.yaw, gravX: g.x, gravY: g.y, gravZ: g.z, cueTimestamp: cues.last)) }
    private func makeResult(samples: [MotionSample], duration: TimeInterval) -> TrialResult { let acc = samples.map(\.accelerationMagnitude), rot = samples.map(\.rotationMagnitude); let avgA = acc.isEmpty ? 0 : acc.reduce(0, +) / Double(acc.count), avgR = rot.isEmpty ? 0 : rot.reduce(0, +) / Double(rot.count); let onset = samples.first { $0.accelerationMagnitude > max(0.25, avgA * 1.8) || $0.rotationMagnitude > max(0.6, avgR * 1.8) }; let timing = onset.flatMap { s in cues.min(by: { abs($0.timeIntervalSince(s.wallTime)) < abs($1.timeIntervalSince(s.wallTime)) }).map { $0.timeIntervalSince(s.wallTime) } }; return TrialResult(movement: movement, placement: placement.rawValue, speed: speed.title, duration: duration, sampleCount: samples.count, peakAcceleration: acc.max() ?? 0, averageAcceleration: avgA, peakRotation: rot.max() ?? 0, averageRotation: avgR, dominantAccelerationAxis: dominant(samples.map { ($0.accX, $0.accY, $0.accZ) }), dominantRotationAxis: dominant(samples.map { ($0.rotX, $0.rotY, $0.rotZ) }), onsetText: onset.map { String(format: "%.2f s", $0.wallTime.timeIntervalSince(trialStart ?? $0.wallTime)) } ?? "No clear threshold", timingDifference: timing, samples: samples) }
    private func dominant(_ vectors: [(Double, Double, Double)]) -> String { guard !vectors.isEmpty else { return "—" }; let sum = vectors.reduce((0.0,0.0,0.0)) { ($0.0 + abs($1.0), $0.1 + abs($1.1), $0.2 + abs($1.2)) }; return sum.0 >= sum.1 && sum.0 >= sum.2 ? "X" : (sum.1 >= sum.2 ? "Y" : "Z") }
    func clearTrials() { trials = []; latestResult = nil; csvURL = nil }
    func prepareCSV() { let header = "timestamp,challengeResponse,movement,placement,speed,userAccX,userAccY,userAccZ,rotX,rotY,rotZ,roll,pitch,yaw,gravX,gravY,gravZ,cueTimestamp\n"; let formatter = ISO8601DateFormatter(); let rows = trials.flatMap(\.samples).map { s in [formatter.string(from: s.wallTime), s.challenge, s.movement, s.placement, s.speed, s.accX, s.accY, s.accZ, s.rotX, s.rotY, s.rotZ, s.roll, s.pitch, s.yaw, s.gravX, s.gravY, s.gravZ, s.cueTimestamp.map(formatter.string) ?? ""].map { "\($0)".replacingOccurrences(of: ",", with: " ") }.joined(separator: ",") }.joined(separator: "\n"); let url = FileManager.default.temporaryDirectory.appendingPathComponent("motion-lab-\(Int(Date().timeIntervalSince1970)).csv"); try? (header + rows).write(to: url, atomically: true, encoding: .utf8); csvURL = url }
}
